### ISSUE TITLE
other file formats

### ISSUE THREAD

**Issue by incanus** [mapbox/takeout#3]
Support the whole complement of file types that geojson.io can handle. 

Will probably rely on #1 file picker to avoid nasty long data URIs.

**Comment by tmcw** [comment]
Right now the URL api is somewhat limited, and I'm not sure whether I should break the assumption that it expects GeoJSON.

**Comment by incanus** [comment]
Huh this is gonna be fun. 

https://github.com/mapbox/geojson.io/blob/122785a852e0ea360c88c1e83691a3b30958b4bf/src/lib/readfile.js

**Comment by incanus** [comment]
Thinking out loud: maybe we should just use the [gist API](http://developer.github.com/v3/gists/) to create a private, anonymous gist and then [pass that to geojson.io](https://github.com/mapbox/geojson.io/blob/122785a852e0ea360c88c1e83691a3b30958b4bf/API.md#idgist) instead of doing `togeojson` magic locally. Would help with App Store #9 too to not have to shell out.

**Comment by incanus** [comment]
Above doesn't help. Explored calling various `geojson.io` code via JavaScriptCore but not workable. Probably will have to just ship command-line `togeojson` unless a real upload API takes shape.

**Comment by incanus** [comment]
Command-line `togeojson` is also going to require `node` being shipped with the app. 

Looked into possibilities for DOM parsing within JavaScriptCore in order to pass documents to `toGeoJSON.kml()` and `toGeoJSON.gpx()` but no dice.

**Comment by tmcw** [comment]
Eh, I'll just implement conversion in the URL api

**Comment by incanus** [comment]
Awesome, that'd be great.

**Comment by incanus** [comment]
Punting on this for now. Defer to website version.
