### ISSUE TITLE
two-way integration

### ISSUE THREAD

**Issue by incanus** [mapbox/takeout#5]
Show latest upload gists in menu for easy recall. Relies on #2 menu.

**Comment by incanus** [comment]
No API for this as of yet -- not going to be possible to get resulting `geojson.io` URL after processing.

**Comment by tmcw** [comment]
Hm, no API for which part? Do you mean GitHub Gists? If you post to gist instead of using the data-uri approach, you can know the resulting URLs (and also have a much higher max file size)

**Comment by incanus** [comment]
Ah, I wasn't aware of this. So if I make a gist of GeoJSON data, pass that to `id=gist:`, the resulting `geojson.io` map will be the same `id`? What about if doing #3 other file formats? Data would go in as one gist (e.g. KML) and would come out as another (GeoJSON).

**Comment by tmcw** [comment]
I'd rather keep the import API simple and not have it autoconvert Gist contents; the complexity of geojson.io needs to be relatively directed or it will creep.

**Comment by incanus** [comment]
Then I'm not sure I understand: 

>  If you post to gist instead of using the data-uri approach, you can know the resulting URLs

Unless you just mean that two-way will only work for GeoJSON (which may be what you're saying). 

That leads to a scenario when only your most recent _GeoJSON_ uploads are in the menu, which is sort of confusing.

**Comment by incanus** [comment]
> Unless you just mean that two-way will only work for GeoJSON (which may be what you're saying).

Doing this.
